version: "2.1"
services:
  arp_proxy:
      container_name: arp_proxy
      image: suhasi/platform-sys:latest
      volumes:
        - ./dev_src/:/src
      networks:
         net-in:
           ipv4_address: 192.168.100.250
      stdin_open: true
      privileged: true
      cap_add:
        - ALL
      tty: true
      cpus: 1.0
      mem_limit: '2000000000'
      memswap_limit: '2000000000'
      mem_swappiness: 0
      command:
        /bin/bash
  arp_probe:
      container_name: arp_probe
      image: suhasi/platform-sys:latest
      volumes:
          - ./probe_src:/src
      networks:
       net-in:
         ipv4_address: 192.168.100.251
      stdin_open: true
      privileged: true
      cap_add:
        - ALL
      tty: true
      cpus: 2.0
      mem_limit: '2000000000'
      memswap_limit: '2000000000'
      mem_swappiness: 0

networks:
  net-in:
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
        